# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "cicd" ]
  pull_request:
    branches: [ "cicd" ]

permissions:
  contents: read

env:
  CREDENTIALS_PATH: ${{ secrets.CREDENTIALS_PATH }}

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        pipx install poetry
        
    - name: Install dependencies
      run: |
        poetry init 
        poetry add gspread
        poetry add selenium
        poetry add webdriver_manager
        poetry add black
        poetry add pylint
        poetry add pytest
    - name: Format code with Black
      run: |
        cd gspread_pkg
        poetry run black *.py
        
    - name: Lint code with pylint
      run: |
        cd gspread_pkg
        poetry run pylint *.py
      continue-on-error: true
    - name: Test with pytest
      run: |
        cd gspread_pkg
        poetry run pytest
